### ISSUE TITLE
Anonymous using?

### ISSUE THREAD

**Issue by joeedh** [tc39/proposal-explicit-resource-management#228]
I was wondering why a syntax like `using lock()` is not in the proposal.  I couldn't find much public discussion of it, but while perusing the standard [I noticed this ](https://tc39.es/ecma262/#sec-identifiers)
![image](https://github.com/tc39/proposal-explicit-resource-management/assets/3221485/0a55a840-f30b-44d9-bb88-eba55b16716b)

Is this the reason why anonymous `using` is not supported, to avoid ASI hacks? It would be really nice to have `using object.lock()` but I can see how adding yet more grammar hacks to the language might not be a good idea.

**Comment by rbuckton** [comment]
There are two scenarios for an "anonymous `using`":
- `using` without introducing a binding
- `using` in an expression position

For "`using` without introducing a binding", we have the [Discard Binding proposal](https://github.com/tc39/proposal-discard-binding). This was originally part of this proposal but was cut prior to Stage 3 and is instead being pursued as a separate proposal. Supporting locking scenarios is a major motivation for this proposal since we have been discussing the introduction of Mutex in the [Shared Structs proposal](https://github.com/tc39/proposal-structs):

```js
{
  // take exclusive lock over some shared data
  using void = new UniqueLock(mutex);
  doSomethingWithSharedData(sharedData);  
} // lock is released
```

For "`using` in an expression position", explicit syntax for that was rejected for the following reasons:

1. `using` _MemberExpression_ is ambiguous with _CallExpression_:
   ```js
   const x = using (y);
   const x = using (y).z;
   ```
4. To ensure scope effects from `using` and `await using` are explicitly discoverable at the start of a _Statement_:
  ```js
  {
    using x = ...;
    await using y = ...;
  }
  ```
  vs.
  ```js
  {
    const x = someArbitrarilyLongAndComplexExpression1(using ...);
    const y = someArbitrarilyLongAndComplexExpression2(await using ...);
  }
  ```
  
(2) is especially important for `await using` since it introduces an implicit `await` at the end of the block.

However, you can still achieve "`using` in an expression position" through the use of `DisposableStack`/`AsyncDisposableStack`, which still maintains the invariant in (2):

```js
{
  await using stack = new AsyncDisposableStack();
  const x = someArbitrarilyLongAndComplexExpression1(stack.use(...));
  const y = someArbitrarilyLongAndComplexExpression2(stack.use(...));
}
```
